name: INDiECAR-RTN-Enviornment
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pyomo=6.1.2
  - cloudpickle=2.1.0
  - geopandas=0.10.0
  - numpy=1.20.3
  - pandas=1.3.3
  - matplotlib=3.4.3
  - scipy=1.7.1